### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gtanime** [dynamiquel/Game-Bar-Browser#17]
no issue here you may close if need be but this is an awesome extension keep up the good work, but may i ask when it will this be available in the US store for v2? i tried updating via package but says not a trusted app i would love to use the favorite option

**Comment by dynamiquel** [comment]
Hi, v2.0 should be released on the Microsoft Store today for everyone. There was some holdback on Microsoft's side, sorry for the delay.

**Comment by dynamiquel** [comment]
I still have no idea how Sideloading works. Every time I try to do it, someone always claims the app is not trusted.
