### ISSUE TITLE
Render time is too high

### ISSUE THREAD

**Issue by dynamiquel** [dynamiquel/Game-Bar-Browser#2]
The browser takes a very long time to render pages and is very noticeable on websites that feature many videos or images.

**Comment by ddasutein** [comment]
If I'm not mistaken, the UWP Web View is still based on the old Edge engine. So I suspect some websites do not play nice with it, especially if you happen to browse any of Google's services (e.g., YouTube). Unfortunately, it will be a while before Microsoft can bring WebView2 which is powered by Chromium.
