### ISSUE TITLE
Bookmark and Default Browser are the same key combos - Ctrl+D.

### ISSUE THREAD

**Issue by gaussandhisgun** [dynamiquel/Game-Bar-Browser#35]
![изображение](https://user-images.githubusercontent.com/63512006/126558975-2b61dbad-4ba6-476a-bd8b-2443cced663a.png)

**Comment by dynamiquel** [comment]
Thanks for bringing that to my attention. I guess I chose Ctrl+D because of 'D efault browser', forgetting that bookmarking also uses it.

**Comment by dynamiquel** [comment]
Fixed in https://github.com/dynamiquel/GameBarBrowser/tree/webview2.
