### ISSUE TITLE
On low resolutions the widget is unusable

### ISSUE THREAD

**Issue by gaussandhisgun** [dynamiquel/Game-Bar-Browser#36]
It takes the whole screen, and if I try to resize it using the somehow visible bottom edge, it disappears completely, probably to the top of Game Bar.
![изображение](https://user-images.githubusercontent.com/63512006/126559447-e6c78e14-e953-442c-ba9a-cfe600972e47.png)
You see that line of slightly-lighter pixels at the top of the screen? That's your browser.

**Comment by dynamiquel** [comment]
Sorry about that but I'm not sure if I can fix that, but the next update (whenever that may be) will feature a smaller minimum size.

**Comment by dynamiquel** [comment]
I'm not entirely sure how to solve this problem you are having.
The solutions that have been added to https://github.com/dynamiquel/GameBarBrowser/tree/webview2 include:
- Smaller minimum size.
- Recentre shortcut (F9)
