### ISSUE TITLE
Custom protocols make it die

### ISSUE THREAD

**Issue by gaussandhisgun** [dynamiquel/Game-Bar-Browser#37]
Input something like chrome://settings or gravitos://nope into adrbar, and browser will hang on for a minute and crash. Firefox just does a search if it does not see a protocol, but this thing chose the easy way out.

**Comment by dynamiquel** [comment]
I'll look into it.

**Comment by dynamiquel** [comment]
Fixed in https://github.com/dynamiquel/GameBarBrowser/tree/webview2.
