### ISSUE TITLE
Twitch don't work

### ISSUE THREAD

**Issue by Sinusflorian** [dynamiquel/Game-Bar-Browser#42]
Hello, wanted to check out after a while the APP again but unfortonally Twitch still don't work, now the Website is loading BUT the Streams just endlessly are Circlying... i use meanwhile a other program for Pin Videos, but it is very buggy. May i ask if there will be one day a possiblilty solve this? For me and many others with 1 Monitor this is bad. 
![Screenshot (93)](https://user-images.githubusercontent.com/93134772/175827591-7a939a69-a426-4cb9-9030-5685a2334b74.png)
^^

Thanks for reading. :)

**Comment by dynamiquel** [comment]
WebView2 has yet to be implemented. I haven't checked if there have been any updates to the Game Bar SDK or WebView2 that fixes the issues I were experiencing when I was attempting to implement WebView2 before.

Sorry, but I have been very busy lately and haven't had the time to keep updated on the Game Bar SDK and to keep re-experimenting after every update. But if anyone has knowledge about this, they can feel free to fork the [**webview2** ](https://github.com/dynamiquel/GameBarBrowser/tree/webview2) branch and make any pull requests.
