### ISSUE TITLE
Icon is too small in menu and bar

### ISSUE THREAD

**Issue by totallymonkey** [dynamiquel/Game-Bar-Browser#9]
I am a developer on the Game Bar team, and we are currently in the process of updating our guidance for icons to make it more clear how the default package icons are used within Game Bar.

If you are relying on the generated package icons for your widget, Game Bar will use the Square150x150Logo* asset. When using Visual Studio to generate your assets, you need to uncheck 'Apply recommended padding' or VS will generate the assets with too much padding for Game Bar.

There is also the option of providing custom override icons, per the documentation here: https://docs.microsoft.com/en-us/gaming/game-bar/guide/icons
You can do this if you want better control over the icons that are being used within Game Bar.

In addition to this, I also noticed that there are no light theme variations of the Square150x150Logo* assets, so when Game Bar is in light theme you can't see your icons. I could file a separate issue for this if you like, just let me know.

Please let me know if you have any questions, comments, or concerns about this. Thanks!

**Comment by dynamiquel** [comment]
I may try your solutions later. I'm currently occupied. Thanks for the help!

I did attempt to use the custom override option but to no success, I may have missed something.

I also attempted to use the Settings widget that is provided with the SDK but clicking the button on the main widget never opened the specified settings widget. I'm not sure if this is a bug on my end or the SDK/guide.

**Comment by totallymonkey** [comment]
When you have time it would be great if you could let me know what issues you had with the custom icons. I would be interested to use your feedback to see where we can improve the documentation. If you wanted to provide me with your original, high quality asset for your icon I could probably find some time to update your project, so let me know.

For the settings, take a look in our Samples at WidgetAdvSampleCS. If you look in Widget1.xaml.cs, you can see there that you will need to register for the SettingsClicked event that is on the XboxGameBarWidget object. When the user clicks the settings button in Game Bar you will get this event. If you simply wish to launch settings every time the user clicks the button you can just call ActivateSettingsAsync that is also on the XboxGameBarWidget object from your event handler. When this happens you will get another OnActivated event in your app, but this time the AppExtensionId on the event args object will be for your specified settings widget.

It looks like our documentation is lacking in this area so I'll get an item on our end filed to improve that.

Thank you for your feedback, and please don't hesitate to reach out to me with any additional questions!

**Comment by dynamiquel** [comment]
Fixed in an upcoming commit.

**Comment by totallymonkey** [comment]
Just checked it out, and it looks great now! We seem to have a bug on our side where an updated app still uses the old icon for some amount of time. Unsure about it yet, but I will look into it.
